### ISSUE TITLE
php-ml source link in composer.lock file  

### ISSUE THREAD

**Issue by ElyesMejri** [akondas/code-review-estimator#3]
Hi

I think that the link for the source php-ml library have to be change from GitHub (https://github.com/php-ai/php-ml.git") to GitLab ("https://gitlab.com/php-ai/php-ml")
because isn't available anymore in Github

**Comment by akondas** [comment]
Thanks, updated in https://github.com/akondas/code-review-estimator/commit/12da751038c9816c2536f9d362d7dcbb2f207a9e
